//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWA_MI1_IvanKozul_2RP1 {
    
    
    public partial class EditData {
        
        /// <summary>
        /// phPersons control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phPersons;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new RWA_MI1_IvanKozul_2RP1.Master Master {
            get {
                return ((RWA_MI1_IvanKozul_2RP1.Master)(base.Master));
            }
        }
    }
}
