//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWA_MI2_IvanKozul_2RP1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drzava
    {
        public int IDDrzava { get; set; }
        public string Naziv { get; set; }
    }
}
